version: "3"

networks:
  my_net:
    name: my_net

volumes:
  my_wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Inception/srcs/requirements/wordpress/wordpress_data
  mydb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Inception/srcs/requirements/mariadb/mysql_data

services:
  webserve:
    image: webserve
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - my_net
    tty: yes
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/default_file:/etc/nginx/sites-available
      - my_wp:/var/www/html
    container_name: my_nginx
    depends_on :
      word:
        condition: service_started
  word:
    image: word
    networks:
      - my_net
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    tty: yes
    container_name: my_word_press
    volumes:
      - my_wp:/var/www/html
      - ./requirements/wordpress/d_conf:/etc/php/7.3/fpm/pool.d
    depends_on:
      db:
        condition: service_started
    env_file:
      - .env
    restart: always
  db:
    image: db
    networks:
      - my_net
    #image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    tty: yes
    container_name: my_db
    env_file:
      - .env
    restart: always
    volumes:
      - mydb:/var/lib/mysql
      - ./requirements/mariadb/conf_file/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf

