version: "3"

volumes:
  my_wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/wordpress_data
  mydb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/mysql_data

services:
  webserve:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    tty: yes
    ports:
      - "443:443"
    volumes:
      - ./nginx/test_ingd:/etc/nginx/sites-available
      - my_wp:/var/www/html
    container_name: my_nginx
    depends_on :
      - word
  word:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    tty: yes
    container_name: my_word_press
    volumes:
      - my_wp:/var/www/html
      - ./wordpress/d_conf:/etc/php/7.3/fpm/pool.d
    depends_on:
      - db
    env_file:
      - .env
    restart: always
  db:
    #image: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    tty: yes
    container_name: my_db
    env_file:
      - .env
    restart: always
    volumes:
      - mydb:/var/lib/mysql

